# Modules of the plugin implement different features.
modules:
  # Lead placement module allows players to place wires using lead item.
  leadPlacement:
    # If false, lead placement will be disabled.
    enabled: true
    # Max length of the lead. If exceeded, player will receive a message.
    maxLength: 10
    # If true, player can continue placing leads after placing one,
    # new lead will start from second point of the last lead.
    continueFromLastPoint: true
    # Permission to place leads. If empty, permission will not be checked.
    # If permission is set and player has no such permission, player will receive a message.
    permission: ''
    # All blocks allowing a lead to be placed on them.
    # This list works both for the legacy (1.12-) and flattened (1.13+) versions.
    allowedBlocks:
      - 'FENCE'
      - 'OAK_FENCE'
      - 'SPRUCE_FENCE'
      - 'BIRCH_FENCE'
      - 'JUNGLE_FENCE'
      - 'ACACIA_FENCE'
      - 'DARK_OAK_FENCE'
      - 'COBBLE_WALL'
      - 'COBBLESTONE_WALL'
      - 'MOSSY_COBBLESTONE_WALL'
      - 'BRICK_WALL'
      - 'PRISMARINE_WALL'
      - 'RED_SANDSTONE_WALL'
      - 'MOSSY_STONE_BRICK_WALL'
      - 'GRANITE_WALL'
      - 'STONE_BRICK_WALL'
      - 'NETHER_BRICK_WALL'
      - 'ANDESITE_WALL'
      - 'RED_NETHER_BRICK_WALL'
      - 'SANDSTONE_WALL'
      - 'END_STONE_BRICK_WALL'
      - 'DIORITE_WALL'
    # Messages sent to players.
    messages:
      firstPointSet: '&aFirst point of the lead set'
      firstPointReset: '&7First point has been reset'
      wirePlaced: '&aThe lead has been placed'
      tooLong: '&cThe lead is too long, limit is %s blocks'
      noPermission: '&cYou have no permission to place leads'